### ISSUE TITLE
404 error - Public key needed

### ISSUE THREAD

**Issue by ghost** [DannyBen/secret_hub#12] opened 2021-08-17 14:42 UTC
Just came across your cli. Really good idea. When I was gonna test it it was giving me this error:

SecretHub::APIError
[404] {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/actions#get-a-repository-public-key"}

**Comment by DannyBen** [comment] 2021-08-17 15:49
1. What command were you trying
2. Did you set `GITHUB_ACCESS_TOKEN`
3. Is it a private or public repo

**Comment by ghost** [comment] 2021-08-17 16:40
1. Bulk and repo 
    - secrethub bulk save secrethub.yml
           -secrethub.yml example:
              user/repo:
              SECRET: TEST_SECRET1
              PASSWORD: 12345
              
              user/rep1:
              SECRET: TEST_SECRET1
              PASSWORD: 12345

    - secrethub repo save user/repo TEST_SECRET 12345
2. Yeah. Used: export GITHUB_ACCESS_TOKEN=TOKEN
3. Public repo.

**Comment by DannyBen** [comment] 2021-08-17 19:32
I am unable to reproduce the problem, except when I am going to an invalid (really not found) repo.

Make sure that [your github token](https://github.com/settings/tokens) has the `repo` scope, and then try the simplest command:

`$ secrethub repo list you/your_repo`

It should display an empty list (or a list of secrets, if you have any on the repo), but should work without an error.

If this doesn't work, I am really unsure what can be the next debugging step.

---

EDIT: What is the public repo you are using it with? (since I see that you have no repos....) Is there a chance it is a legacy repo, as mentioned in the [provided error link](https://docs.github.com/en/rest/reference/actions#get-a-repository-public-key%22%7D)? Or perhaps you are trying it on a repo that you are not its owner?

**Comment by DannyBen** [comment] 2021-08-17 19:47
Oh - another idea, if any of the above is still not helpful.
Try running the same list command (or other simple command that fails) but set the `DEBUG` environment variable to `1` before running the command:

`$ DEBUG=1 secrethub repo list you/repo`

This should give more details on where exactly it failed (but I still doubt there is anything wrong with the gem itself).

**Comment by ghost** [comment] 2021-08-17 20:09
I hate to be that guy...it was my bad. I forgot to add to my token the repo scope. Had the org scope but I was adding the secret at the repo level...
I'm sorry for bothering you.

It worked like a charm!. You made my life easier with this cli. Thanks a lot!

**Comment by DannyBen** [comment] 2021-08-17 20:17
Oh that is great, but a little weird - I tested it without the `repo` scope, and it gave me a different error clearly stating that I need admin rights.

Anyways - glad it's working now.

I will go ahead and close this ticket, but feel free to comment here or open a new one if any other issue comes up.

**Closed as completed by DannyBen** 2021-08-17 20:17 UTC
Labels: question
